# Generated by Django 2.2.4 on 2019-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('schoolName', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=10)),
                ('marks', models.CharField(max_length=10)),
                ('stateRank', models.CharField(max_length=10)),
                ('award', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
